name = "Farmer Market"
author = "ME"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8b91186f87618526ce5f86fc3bac2099df185cf1c39a21893f774aa347487ce2"

[versions]
forge = "14.23.5.2847"
minecraft = "1.12.2"
